baseURL = "https://tradusquare.github.io"
languageCode = "en-us"
theme="default"
title = "TraduSquare"
paginate=5
[Params]
  subtitle = "Rincón del traductor español"
  logo = "img/srm.png"
  favicon = "img/favicon.ico"
  commit = false
  
[permalinks]
  post = "/:title/"